repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        stages: [commit]
        language: system
        entry: autoflake
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-unused-variables"
          - "--ignore-init-module-imports"
        types: [python]

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: isort
        args: ["--profile", "black", "--filter-files"]
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]
