version: "3.8"
services:
  qrt-api:
    image: ${IMAGE_NAME}:${TAG}
    volumes:
      - ./app:/code/app
    ports:
      - 8080:8080
    restart: on-failure
    command: "uvicorn app.app:app --host 0.0.0.0 --port 8080"
